name: VPinballX.starter
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build-server:
    name: Build VPinballX.starter-${{ matrix.config }}-win-${{ matrix.platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            config: Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          SHA7="${GITHUB_SHA::7}"
          TAG="${VERSION}-${SHA7}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          ASSEMBLY_INFO="VPinballX.starter/VPinballX.starter.csproj"
          VERSION=$(grep -Eo "<AssemblyVersion>" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
      - name: Build VPinballX.starter
        run: |
          cd VPinballX.starter
          dotnet publish -r ${{ matrix.rid }} -c ${{ matrix.config }} -p:PublishSingleFile=true -p:PublishTrimmed=true
      - name: Bundle 
        run: |
          mkdir tmp  
          cp VPinballX.starter/bin/Release/net6.0-windows/win-x64/publish/VPinballX.starter.exe tmp
          cp README.md tmp
      - uses: actions/upload-artifact@v3
        with:
          name: VPinballX.starter-${{ steps.version.outputs.tag }}-${{ matrix.config }}-${{ matrix.rid }}
          path: tmp

