name: VPinballX.starter
on:
  push:

env:
  ACTIONS_RUNNER_DEBUG: true

defaults:
  run:
    shell: bash

jobs:
  build-server:
    name: Build VPinballX.starter-${{ matrix.config }}-win-${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            config: Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          echo run_id ${{ github.run_id }}
          echo run_number ${{ github.run_number }}
          echo run_attempt ${{ github.run_attempt }}
          SHA7="${GITHUB_SHA::7}"
          ASSEMBLY_INFO="VPinballX.starter/VPinballX.starter.csproj"
          VERSION=$(grep -Eo "<Version>.*" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1).${{ github.run_number }}
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/<Version>.*</<Version>${TAG}</g" "${ASSEMBLY_INFO}"
          YEAR="$(date +'%Y')"
          perl -i -pe"s/COPYRIGHTYEAR/${YEAR}/g" "${ASSEMBLY_INFO}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Build VPinballX.starter
        run: |
          cd VPinballX.starter
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet publish -r ${{ matrix.rid }} -c ${{ matrix.config }} --self-contained false -p:PublishSingleFile=true
      - name: Bundle 
        run: |
          mkdir tmp  
          cp VPinballX.starter/bin/Release/net8.0-windows/win-x64/publish/VPinballX.starter.exe tmp

          cp README.md tmp/VPinballX.starter.ReadMe.txt
          cp LICENSE tmp/LICENSE.GPL3
          cat doc/*.LICENSE.txt > tmp/VPinballX.starter.licenses.txt
      - uses: actions/upload-artifact@v4
        with:
          name: VPinballX.starter-${{ steps.version.outputs.tag }}-${{ matrix.config }}-${{ matrix.rid }}
          path: tmp

